### ISSUE TITLE
yast security crashing in text mode

### ISSUE THREAD

**Issue by jsuchome** [yast/ycp-killer#441]
Running 'yast security' crashes with 

2013-06-05 15:08:50 <3> linux-yp2z(1775) [Ruby] ycp/wfm.rb:85 Client call failed with undefined method `Tree' for YCP::UIShortcuts:Module and backtrace [
     "/usr/share/YaST2/modules/Wizard.rb:665:in`CreateTree'",
     "/usr/share/YaST2/clients/security.rb:751:in `TreeDialog'",
     "/usr/share/YaST2/clients/security.rb:816:in`block in SecuritySequence'",
     "/usr/lib64/ruby/vendor_ruby/2.0.0/ycp/builtins.rb:501:in `call'",
     "/usr/lib64/ruby/vendor_ruby/2.0.0/ycp/builtins.rb:501:in`eval'",
     "/usr/share/YaST2/modules/Sequencer.rb:179:in `WS_run'",
     "/usr/share/YaST2/modules/Sequencer.rb:237:in`Run'",
     "/usr/share/YaST2/clients/security.rb:824:in `SecuritySequence'",
     "/usr/lib64/ruby/vendor_ruby/2.0.0/ycp/fun_ref.rb:16:in`call'",
     "/usr/lib64/ruby/vendor_ruby/2.0.0/ycp/fun_ref.rb:16:in `call'",
     "/usr/share/YaST2/modules/CommandLine.rb:855:in`Run'",
     "/usr/share/YaST2/clients/security.rb:53:in `main'",
     "/usr/share/YaST2/clients/security.rb:899:in`<top (required)>'",
     "/usr/lib64/ruby/vendor_ruby/2.0.0/ycp/wfm.rb:83:in `eval'",
     "/usr/lib64/ruby/vendor_ruby/2.0.0/ycp/wfm.rb:83:in`run_client'"
]

Other modules with Tree widget are probably affected too.

**Comment by jsuchome** [comment]
Works fine with latest yast2 package.
